name: docker-build

on:
  workflow_dispatch:    # Trigger manually from the GitHub UI
    # Uncomment and modify the following line if you want to trigger on specific branches
    # branches:
    #   - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build Docker image
        run: |
          docker build -t docker-build .

